# Importing NumPy

In [1]:
import numpy as np

# Creating NumPy array

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int64')

In [6]:
b = np.array([9.0, 3.4, 2.33])
b

array([9.  , 3.4 , 2.33])

In [8]:
b.dtype

dtype('float64')

## Getting General Properties of an array

In [9]:
twoDim = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype='int16')
print(twoDim)
print(f'Shape: {twoDim.shape}')
print(f'element count: {twoDim.size}')
print(f'Dimension: {twoDim.ndim}')
print(f'DataType: {twoDim.dtype}')
print(f'Individual element size: {twoDim.itemsize}bytes')
print(f"Total Size = t_item*ind_size = {twoDim.size*twoDim.itemsize}bytes")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
element count: 9
Dimension: 2
DataType: int16
Individual element size: 2bytes
Total Size = t_item*ind_size = 18bytes


In [18]:
y = np.array([500, 4, 5], dtype='int8')
print(y)
# for 8 bit, from -128 to 127 is the range of numbers that can be stored

[-12   4   5]


## Accessing specific elements

In [20]:
twoDim = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype='int16')
#getting specific element array[r, c]
print(twoDim[1, 2])

#gettin specific colum n array[:, n]
print(twoDim[:, 0])

#getting specific row m array[m, :]
print(twoDim[1, :])

6
[1 4 7]
[4 5 6]


In [22]:
m = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#array[startIndex:endIndex:stepSize]
print(m[2:8:2])

[2 4 6]


## Changing value/s of element/s

In [24]:
twoDim = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype='int16')
print(twoDim)

#changing values of a column
twoDim[:, 2] = [1, 2, 3]
print(twoDim)

#changing values of a column
twoDim[2, :] = [1, 1, 1]
print(twoDim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 1]
 [4 5 2]
 [7 8 3]]
[[1 2 1]
 [4 5 2]
 [1 1 1]]


## Special usefull methods

In [27]:
#all zeros, all ones
print(np.zeros(5))
print(np.ones((3, 3)))

#any other than zeros or ones
print(np.full((4, 2, 3),2))

#to use the similar dimension of another array
print(np.full_like(a, 4))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]
[4 4 4]


In [65]:
#random Integers: (range, size/shape)
np.random.randint(10, size=(3,3))

array([[2, 5, 5],
       [6, 5, 7],
       [1, 1, 2]])

In [66]:
#random Decimal numbers: (r, c)
np.random.rand(4, 2)

array([[0.4160099 , 0.0206774 ],
       [0.14016035, 0.66918333],
       [0.01158293, 0.75812723],
       [0.38048849, 0.41636529]])

In [67]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
#repeat an array
arr = np.array([[1, 2, 3]])
print(arr.shape)
r1 = np.repeat(arr, 3, axis=0)
r1

(1, 3)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Craete the following array using NumPy
[[1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 9. 0. 1.]

 [1. 0. 0. 0. 1.]
 
 [1. 1. 1. 1. 1.]]

In [28]:
ones = np.ones((5,5))
zeros = np.zeros((3,3))
zeros[1,1] = 9
print(zeros)
print(ones)

ones[1:4,1:4] = zeros
print(ones)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Caution for copying from an array!

In [31]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(b)
print(a) #changing b also changes a

#Use copy() method to aviod this issue
x = np.array([1, 2, 3])
b = x.copy()
b[0] = 100
print(b)
print(x)

[100   2   3]
[100   2   3]
[100   2   3]
[1 2 3]


## Element-wise basic algebraic operations

In [38]:
a = np.array([1, 2, 3, 4])
b = np.array([8, 7, 6, 5])

print(a+b)
print(a-b)
print(b/a)
print(a*b)
print(2*a)
print(b-3)

[9 9 9 9]
[-7 -5 -3 -1]
[8.   3.5  2.   1.25]
[ 8 14 18 20]
[2 4 6 8]
[5 4 3 2]


#### Linear algebra

In [39]:
# Matrix Multiplication
a = np.ones((2, 3)) # 2x3
b = np.full((3, 2), 2) # 3x2
np.matmul(a,b) # 2x2

array([[6., 6.],
       [6., 6.]])

In [40]:
# Determinants
i = np.identity(3)
np.linalg.det(i)

1.0

In [41]:
#Inverse
P = np.array([[1, 2, 3],
             [0, 2, 6],
             [0, 0, 9]])
print(f"P = {P}")
print(f"Det(P): {np.linalg.det(P)}")
print(f"P-Inverse: {np.linalg.inv(P)}")
print(f"Eigenvalues of P: {np.linalg.eigvals(P)}")

P = [[1 2 3]
 [0 2 6]
 [0 0 9]]
Det(P): 18.000000000000004
P-Inverse: [[ 1.         -1.          0.33333333]
 [ 0.          0.5        -0.33333333]
 [ 0.          0.          0.11111111]]
Eigenvalues of P: [1. 2. 9.]


#### Statistics


In [52]:
a = np.array([1, 2, 3, 4])
print(f"Min: {np.min(a)}")
print(f"Max: {np.max(a)}")
print(f"Sum: {np.sum(a)}")

Min: 1
Max: 4
Sum: 10


In [50]:
#calculating standard deviation manually
import math
x_bar = np.sum(a)/a.size

sq = 0
for x in a:
    sq += (x_bar-x)**2

stdev = math.sqrt(sq/a.size)
print(stdev)


1.118033988749895


In [53]:
#Standard deviation using NumPy std() method
np.std(a)

1.118033988749895

### Reorganizing an array

In [54]:
b = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
print(b)
a = b.reshape(4,2)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [55]:
#vertically stacking vectors or creating matrices
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
#Horizontal stack
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Miscellaneous

   ##### Loading data

In [56]:
data = np.genfromtxt('file.txt', delimiter=',')
dataAsInt = data.astype('int32')
print(data)
print(dataAsInt)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[1 2 3 4]
 [5 6 7 8]]


#### Boolean masking and advanced indexing

In [57]:
dataAsInt[dataAsInt > 2]

array([3, 4, 5, 6, 7, 8], dtype=int32)

In [58]:
#Index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[0, 3, 5, 6, 8]]

array([1, 4, 6, 7, 9])

In [59]:
np.any(dataAsInt > 5, axis=0)

array([False,  True,  True,  True])

In [60]:
np.all(dataAsInt>5, axis=0)

array([False, False, False, False])

In [61]:
(~(data>2) & (data<5))

array([[ True,  True, False, False],
       [False, False, False, False]])

## Diagonal indexing

In [68]:
twoDim = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype='int16')
print(twoDim)

#array[[rows in order], [cols in order]]
primary_diagonal = twoDim[[0,1,2], [0,1,2]]
print(primary_diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [66]:
#secondary diagonal
twoDim[[0, 1, 2], [2, 1, 0]]

array([3, 5, 7], dtype=int16)