In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
type(a)
a.dtype

dtype('int64')

In [5]:
b = np.array([9.0, 3.4, 2.33])
b

array([9.  , 3.4 , 2.33])

In [9]:
type(b)
b.dtype

dtype('float64')

In [35]:
twoDim = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype='int16')
print(twoDim)
print(f'Shape: {twoDim.shape}')
print(f'element count: {twoDim.size}')
print(f'Dimension: {twoDim.ndim}')
print(f'DataType: {twoDim.dtype}')
print(f'Individual element size: {twoDim.itemsize}bytes')
print(f"Total Size = t_item*ind_size = {twoDim.size*twoDim.itemsize}bytes")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
element count: 9
Dimension: 2
DataType: int16
Individual element size: 2bytes
Total Size = t_item*ind_size = 18bytes


In [14]:
x = np.array([1, 2, 3], dtype='int16')
x.ndim

1

In [36]:
print(2**8)

256


In [38]:
y = np.array([300, 4, 5], dtype='int8')
print(y)

[44  4  5]


In [42]:
#getting specific element array[r, c]
print(twoDim[1, 2])

#gettin specific colum n array[:, n]
print(twoDim[:, 0])

#getting specific row m array[m, :]
print(twoDim[1, :])

6
[1 4 7]
[4 5 6]


In [43]:
m = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
#array[start:end:stepSize]
print(m[2:8:2])

[2 4 6]


In [45]:
#changing values of a column or row
twoDim[:, 2] = [1, 2, 3]
print(twoDim)

[[1 2 1]
 [4 5 2]
 [7 8 3]]


In [52]:
#all zeros
print(np.zeros(5))
print(np.ones((3, 3), dtype='int8'))
print(np.full((4, 2, 3),2, dtype='int8'))
print(np.full_like(a, 4))

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]
[4 4 4]


In [65]:
#random Integers: (range, size/shape)
np.random.randint(10, size=(3,3))

array([[2, 5, 5],
       [6, 5, 7],
       [1, 1, 2]])

In [66]:
#random Decimal numbers: (r, c)
np.random.rand(4, 2)

array([[0.4160099 , 0.0206774 ],
       [0.14016035, 0.66918333],
       [0.01158293, 0.75812723],
       [0.38048849, 0.41636529]])

In [67]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
#repeat an array
arr = np.array([[1, 2, 3]])
print(arr.shape)
r1 = np.repeat(arr, 3, axis=0)
r1

(1, 3)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [85]:
#ones
g = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
print(g)

g[1:4,1:4] = z
print(g)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [87]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(b)
print(a)

#Copy
x = np.array([1, 2, 3])
b = x.copy()
b[0] = 100
print(b)
print(x)

[100   2   3]
[100   2   3]
[100   2   3]
[1 2 3]


In [88]:
#We can do element wise basic algebraic operations

#### Linear algebra

In [92]:
# Matrix Multiplication
a = np.ones((2, 3)) # 2x3
b = np.full((3, 2), 2) # 3x2
np.matmul(a,b) # 2x2

array([[6., 6.],
       [6., 6.]])

In [94]:
# Determinants
i = np.identity(3)
np.linalg.det(i)

1.0

In [109]:
#Inverse
P = np.array([[1, 2, 3],
             [0, 2, 6],
             [0, 0, 9]])
print(f"P = {P}")
print(f"Det(P): {np.linalg.det(P)}")
print(f"P-Inverse: {np.linalg.inv(P)}")
print(f"Eigenvalues of P: {np.linalg.eigvals(P)}")

#we can do many more

P = [[1 2 3]
 [0 2 6]
 [0 0 9]]
Det(P): 18.000000000000004
P-Inverse: [[ 1.         -1.          0.33333333]
 [ 0.          0.5        -0.33333333]
 [ 0.          0.          0.11111111]]
Eigenvalues of P: [1. 2. 9.]
Eigenvectors of P: (array([1., 2., 9.]), array([[1.        , 0.89442719, 0.40840458],
       [0.        , 0.4472136 , 0.59404303],
       [0.        , 0.        , 0.6930502 ]]))


#### Statistics


In [110]:
np.min(a)

1.0

In [111]:
np.max(a)

1.0

In [112]:
np.sum(a)

6.0

### Reorganizing

In [115]:
b = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
print(b)
a = b.reshape(4,2)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [116]:
#vertically stacking vectors or creating matrices
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
#Horizontal stack
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Miscellaneous

   ##### Loading data

In [121]:
data = np.genfromtxt('file.txt', delimiter=',')
dataAsInt = data.astype('int32')
print(data)
print(dataAsInt)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[1 2 3 4]
 [5 6 7 8]]


#### Boolean masking and advanced indexing

In [122]:
dataAsInt[dataAsInt > 2]

array([3, 4, 5, 6, 7, 8], dtype=int32)

In [123]:
#Index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[0, 3, 5, 6, 8]]

array([1, 4, 6, 7, 9])

In [127]:
np.any(dataAsInt > 5, axis=0)

array([False,  True,  True,  True])

In [128]:
np.all(dataAsInt>5, axis=0)

array([False, False, False, False])

In [131]:
(~(data>2) & (data<5))

array([[ True,  True, False, False],
       [False, False, False, False]])

In [134]:
#diagonal indexing
print(twoDim)
twoDim[[0,1,2], [0,1,2]]

[[1 2 1]
 [4 5 2]
 [7 8 3]]


array([1, 5, 3], dtype=int16)